name: "PRANC Training of ImageNet-100 with Resnet-18 with multi-GPU with 7,000 alpha"
id: "R18_IMAGENET100"
gpus: [0,1,2,3,4,5,6,7]

pranc:
  seed: 0 
  num_alpha: 7000

experiment:
  mode: 'train'   #[train, test]
  method: 'pranc'    #[normal, pranc, pranc_bin]
  loss: "cross-entropy"   #[cross-entropy, mse]
  lr: 0.001
  optimizer: 'adam'  #[sgd, adam]
  # momentum: 0.9 #momentum for sgd
  # weight_decay: 0.0001 #weight decay for sgd
  scheduler: 'step' #[none, step, exponential]
  gamma: 0.9 #gamma for exponential and step scheduler 
  step: 10  #step for step scheduler
  epoch: 200
  batch_size: 256   #optional for testing
  # resume: 'R18_IMAGENET100/pranc'  #for resuming pranc training. 
  # resume: '<TASK_ID>/best_model.pt'  #for resuming normal training. 
  # load_model: '<TASK_ID>/pranc' #for pranc testing
  # load_model: '<TASK_ID>/best_model.pt' #for normal testing 
  task: 'imagenet100' #[mnist, cifar10, cifar100, tiny, imagenet]
  model_arch: 'resnet18'  #[lenet, resnet18, resnet20, resnet56, alexnet, convnet]

dataset:
  image_width: 256 # set 28 for mnist, 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: '/datasets/imagenet100'    #path to the dataset

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_model.pt'    #if touch, modify resume and load_model
  save_path: 'pranc'      #if touch, modify resume and load_model
